// Sample crew for preview mode only (turn it on/off in your profile). Friends, their
// visits and photos, on 30 real Dubai places it brings with it. Photos are the Stitch
// design images in /demo. Removed completely when the demo is switched off.
export const DEMO = {
  crew: { name:'Karak Crew', tagline:'Chai, saffron buns, and old Deira hideouts', code:'KARAK7' },
  users: [
    { id:'demo-maya',  name:'Maya',  handle:'maya',  tagline:'Chai scout',   avatar:{photo:'demo/d52.jpg'} },
    { id:'demo-omar',  name:'Omar',  handle:'omar',  tagline:'Regag hunter', avatar:{photo:'demo/d17.jpg'} },
    { id:'demo-layla', name:'Layla', handle:'layla', tagline:'Sweet tooth',  avatar:{photo:'demo/d36.jpg'} },
    { id:'demo-kabir', name:'Kabir', handle:'kabir', tagline:'Parotta lead', avatar:{photo:'demo/d14.jpg'} },
    { id:'demo-noor',  name:'Noor',  handle:'noor',  tagline:'Deira native', avatar:{photo:'demo/d24.jpg'} },
  ],
  // the places the sample crew has been (added with the demo, removed with it unless you've logged them)
  venues: [
    ['Trio Cafe (Dubai Mall)','downtown','coffee'], ['Knot Bakehouse','jumeirah','matcha'], ['Ravi Restaurant','satwa','cafeteria'],
    ['Koukh Al Shay','jumeirah','karak'], ['Emmy Squared','jumeirah','pizza'], ['Al Ustad Special Kabab','burdubai','cafeteria'],
    ['Arabian Tea House','burdubai','coffee'], ['Tom & Serg','alquoz','coffee'], ['Nightjar Coffee Roasters','alquoz','coffee'],
    ['RAW Coffee Company','alquoz','coffee'], ['Home Bakery','jumeirah','dessert'], ['Filli Cafeteria','karama','cafeteria'],
    ['Al Mallah','satwa','cafeteria'], ["Mama'Esh",'jumeirah','cafeteria'], ['Al Samadi Sweets & Cafe','downtown','dessert'],
    ["Toby's Estate",'downtown','coffee'], ['Stomping Grounds','jumeirah','coffee'], ['Common Grounds','alquoz','coffee'],
    ['Alma 560 Cafe','alquoz','coffee'], ['Cafe Rider','alquoz','coffee'], ['Society Cafe & Lounge','jumeirah','coffee'],
    ['Bait Al Shay','deira','karak'], ['Chai and Co','deira','karak'], ['Project Chaiwala','jumeirah','karak'],
    ['Salt','umsuqeim','burger'], ['Pitfire Pizza','businessbay','pizza'], ['Pickl','marina','burger'],
    ['Magnolia Bakery','downtown','dessert'], ['Trio Cafe (Jumeirah)','jumeirah','coffee'], ['ABC Coffee Roasters','alquoz','coffee'],
  ],
  // [photo file, caption]
  entries: [
    { user:'demo-maya',  venue:'Trio Cafe (Dubai Mall)', rating:4.5, daysAgo:2, notes:'Get the iced Spanish latte with oat milk, best morning table.', photos:[['d23.jpg','Signature Spanish Latte'],['d34.jpg','Warm Brioche Bun']] },
    { user:'demo-omar',  venue:'Trio Cafe (Dubai Mall)', rating:4, daysAgo:6, notes:'Great seating for work, plenty of sockets along the back banquette.', photos:[['d29.jpg','Corner table']] },
    { user:'demo-noor',  venue:'Trio Cafe (Dubai Mall)', rating:5, daysAgo:12, private:true, notes:'My secret reading spot. Do not tell the crew.', photos:[['d27.jpg','Corner reading nook']] },
    { user:'demo-maya',  venue:'Knot Bakehouse', kind:'want', daysAgo:1 },
    { user:'demo-layla', venue:'Knot Bakehouse', rating:5, daysAgo:4, notes:'The cardamom knot is a must. Go before 10, they sell out.', photos:[['d37.jpg','Cardamom knot'],['d10.jpg','Babka knots']] },
    { user:'demo-kabir', venue:'Ravi Restaurant', rating:5, daysAgo:3, notes:'Legendary butter chicken. Mop it up with two parottas.', photos:[['d19.jpg','Butter chicken & parotta']] },
    { user:'demo-noor',  venue:'Ravi Restaurant', rating:4.5, daysAgo:9, notes:'Still the best cheap eat in Satwa.', photos:[] },
    { user:'demo-maya',  venue:'Koukh Al Shay', rating:4.5, daysAgo:5, notes:'Saffron karak with a regag on the side. Perfect 11pm stop.', photos:[['d04.jpg','Karak in clay'],['d20.jpg','Karak line-up']] },
    { user:'demo-omar',  venue:'Koukh Al Shay', rating:5, daysAgo:14, notes:'Order two. You will want the second one.', photos:[['d43.jpg','Roadside karak']] },
    { user:'demo-kabir', venue:'Emmy Squared', kind:'want', daysAgo:2 },
    { user:'demo-noor',  venue:'Emmy Squared', rating:4.5, daysAgo:7, notes:'That crispy cheese crust on the Detroit square.', photos:[['d44.jpg','Detroit square'],['d31.jpg','Burrata hot honey']] },
    { user:'demo-omar',  venue:'Al Ustad Special Kabab', rating:5, daysAgo:10, notes:'Crispy sumac charred crust, unforgettable.', photos:[['d47.jpg','Saffron kabab & chai']] },
    { user:'demo-noor',  venue:'Arabian Tea House', rating:4, daysAgo:16, notes:'Breakfast under the tree. Zaatar manakeesh and hibiscus.', photos:[['d02.jpg','Al Fahidi alley hidden gem'],['d53.jpg','Under the bougainvillea trellis']] },
    { user:'demo-layla', venue:'Arabian Tea House', rating:4.5, daysAgo:21, notes:'Karak and dates in the courtyard.', photos:[['d51.jpg','Karak & date cookies']] },
    { user:'demo-maya',  venue:'Tom & Serg', rating:4, daysAgo:18, notes:'Brunch classic. The avocado toast holds up.', photos:[] },
    { user:'demo-omar',  venue:'Nightjar Coffee Roasters', rating:4.5, daysAgo:8, notes:'Nitro cold brew and a quiet corner.', photos:[['d09.jpg','Cardamom flat white'],['d15.jpg','V60 pour-over']] },
    { user:'demo-kabir', venue:'Nightjar Coffee Roasters', rating:4, daysAgo:22, notes:'Great beans to take home.', photos:[['d13.jpg','Pour over bar']] },
    { user:'demo-layla', venue:'RAW Coffee Company', rating:4, daysAgo:11, notes:'Saffron latte in a terracotta cup. Cosy.', photos:[['d22.jpg','Saffron latte']] },
    { user:'demo-layla', venue:'Home Bakery', rating:4.5, daysAgo:13, notes:'Sticky toffee and the brioche.', photos:[['d38.jpg','Cardamom coffee bun'],['d39.jpg','Glazed brioche']] },
    { user:'demo-kabir', venue:'Filli Cafeteria', rating:4, daysAgo:5, notes:'Chips oman paratha roll, zafran tea. Midnight fuel.', photos:[['d32.jpg','Chips oman roll']] },
    { user:'demo-noor',  venue:'Al Mallah', rating:4, daysAgo:26, notes:'Shawarma and fresh juice on 2nd December St.', photos:[['d50.jpg','Street food spread']] },
    { user:'demo-maya',  venue:"Mama'Esh", rating:4.5, daysAgo:28, notes:'Manakeesh straight out of the oven.', photos:[['d05.jpg','Flatbreads & dips']] },
    { user:'demo-layla', venue:'Al Samadi Sweets & Cafe', rating:4.5, daysAgo:15, notes:'Luqaimat drowning in date syrup.', photos:[['d21.jpg','Luqaimat']] },
    { user:'demo-omar',  venue:"Toby's Estate", rating:4, daysAgo:20, notes:'Solid flat white, good for meetings.', photos:[] },
    { user:'demo-noor',  venue:'Stomping Grounds', rating:4.5, daysAgo:24, notes:'Sunday brunch, arches and olive trees.', photos:[['d28.jpg','Arched alcoves']] },
    { user:'demo-kabir', venue:'Common Grounds', rating:3.5, daysAgo:30, notes:'Busy but the eggs are good.', photos:[['d40.jpg','Weekend buzz']] },
    { user:'demo-maya',  venue:'Alma 560 Cafe', rating:4, daysAgo:33, notes:'Quiet, green, laptop friendly.', photos:[['d42.jpg','Fig trees and concrete']] },
    { user:'demo-omar',  venue:'Cafe Rider', rating:4, daysAgo:12, notes:'Iced Spanish latte and a pistachio croissant.', photos:[['d07.jpg','Latte & pistachio']] },
    { user:'demo-layla', venue:'Society Cafe & Lounge', rating:4, daysAgo:19, notes:'Iced latte, fluted glass, very photogenic.', photos:[['d12.jpg','Fluted glass latte']] },
    { user:'demo-noor',  venue:'Bait Al Shay', rating:4.5, daysAgo:6, notes:'Karak poured from the brass pot.', photos:[['d46.jpg','Brass pot pour']] },
    { user:'demo-kabir', venue:'Chai and Co', rating:4, daysAgo:9, notes:'Creek-side chai at golden hour.', photos:[['d25.jpg','Creek chai'],['d30.jpg','Tiny cup, big view']] },
    { user:'demo-maya',  venue:'Project Chaiwala', rating:4.5, daysAgo:3, notes:'Karak + bun maska. Always.', photos:[] },
    { user:'demo-layla', venue:'Salt', kind:'want', daysAgo:4 },
    { user:'demo-noor',  venue:'Knot Bakehouse', kind:'want', daysAgo:5 },
    { user:'demo-omar',  venue:'Pitfire Pizza', kind:'want', daysAgo:8 },
    { user:'demo-kabir', venue:'Pickl', rating:4, daysAgo:27, notes:'Chicken sando. Messy, worth it.', photos:[] },
    { user:'demo-layla', venue:'Magnolia Bakery', rating:3.5, daysAgo:35, notes:'Banana pudding, obviously.', photos:[['d33.jpg','Glazed buns']] },
    { user:'demo-maya',  venue:'Trio Cafe (Jumeirah)', rating:4, daysAgo:40, notes:'Same lattes, calmer crowd.', photos:[['d08.jpg','Iced Spanish latte']] },
    { user:'demo-omar',  venue:'ABC Coffee Roasters', rating:4.5, daysAgo:17, notes:'Flat white with rosette art.', photos:[['d11.jpg','Rosette flat white']] },
    { user:'demo-kabir', venue:'Knot Bakehouse', rating:4, daysAgo:23, notes:'Pistachio cream bun.', photos:[['d35.jpg','Cardamom brioche knot']] },
  ],
};
