// Terrain sprites (map-art/<sprite>.png): drawn on the ground, centred on a real point at a whole-number scale
// picked from the real size (scale = art px per sprite px at full size). land: one bit per sprite pixel (1 = land),
// so the map's tiles follow the art for pins and areas. lights: pixels lit at night. Made by tools/terrain-prep.mjs.
export const TERRAINS = [
 {
  "id": "the_world_islands",
  "sprite": "the_world_islands",
  "centre": [
   25.21667,
   55.16667
  ],
  "scale": 4,
  "w": 239,
  "h": 124,
  "source": "Wikipedia, The World (archipelago): 25°13′N 55°10′E, 9 x 6 km. At this projection 9 km east-west is ~1,010 art px; the art is 239 px, so x4 (956 px)",
  "night": {
   "#f4e2b0": "#8a8092",
   "#c4a270": "#6c6476",
   "#a88860": "#564f62",
   "#96e2d6": "#23436c",
   "#7ad4cc": "#1e3c63",
   "#68c8c4": "#19345a"
  },
  "lights": [
   10186,
   10187,
   12098,
   12099,
   12338,
   13540,
   13541,
   13542,
   13780
  ],
  "land": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+A/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAf/gfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6v//v/4PCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9///////XDwAAAAAAAAAAAAAAAAAAAAAAAAAAAOj/////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAwP//////////FwAAAAAAAAAAAAAAAAAAAAAAAAAA/v///////////wAAAAAAAAAAAAAAAAAAAAAAAADA/////6///////xcAAAAAAAAAAAAAAAAAAAAAAAD4//9XAODg/////78AAAAAAAAAAAAAAAAAAAAAAAD//y8AAPzx9/v///8BAAAAAAAAAAAAAAAAAAAAAOD/fwAAAP/4+0P///8PAAAAAAAAAAAAAAAAAAAAAPz/AwAAgH/4/QPg//9/AAAAAAAAAAAAAAAAAAAAgP8fAAAAwD90/gGA////AgAAAAAAAAAAAAAAAAAA8P8DAAAA4B8A/wDg7///BwAAAAAAAAAAAAAAAAAA/n8AAAAA8B8AfwDwQ///LwAAAAAAAAAAAAAAAAAA/w8AAAAA+A/AP1D4Afr/fwAAAAAAAAAAAAAAAADg/wEAAAAA8If+n3/8AND//wAAAAAAAAAAAAAAAADwPwAAAAAA+PP/9z8+AID//wUAAAAAAAAAAAAAAAD8BwAAAAAA/Pn//p8fAAD9/w8AAAAAAAAAAAAAAAD/AAAAAAAA/vx//+8PAAD4/x8AAAAAAAAAAAAAAMB/AAAAAAAA//6///8HAADQ/z8AAAAAAAAAAAAAAPAPAAAAAADAf//P//8DAACA/38AAAAAAAAAAAAAAPgHAAAAAAD4v//jP/4BAAAA//8AAAAAAAAAAAAAAPwAAAAAAAD8H/rzA/8AAAAA+P8BAAAAAAAAAAAAAH8AAAAAAAD+D/75gx8AAAAA8P8DAAAAAAAAAAAAgB8AAAAAAAD/A//8gQMAAAAA4P8HAAAAAAAAAAAA4AcAAAAAAID/gX/+AwAAAAAAwP8PAAAAAAAAAAAA8AMAAAAAAMAvwD//AQAAAAUAgP8fAAAAAAAAAAAA+AAAAAAAAMAB4I//AAAAwA8AAP8/AAAAAAAAAAAAfAAAAAAAAAAQ4IN/AAAA4A8AAP5/AAAAAAAAAAAAHgAAAAAAAAB/QAA/AAAA8I8+APz/AAAAAAAAAAAADwAAAAAAAMA/AIAOAAAA+M9/APj/AQAAAAAAAACABwAAAAAAAOAfAAAAAAAA/Oc/APD/AwAAAAAAAADAAwAAAAAAAPAPAAAAAAAA/vM/AOD/AwAAAAAAAADgAQAAAACAPvgHAAAAAAAA/vkfAMD/AwAAAAAAAADwAAAAAADQH/wDAAAAAAAA/vwPAID/BwAAAAAAAAB4AAAAAAD4D/4BAAAAAADgHfw/AAD/DwAAAAAAAAA8AAAAAAD8B34AAAAAAAB4CPg/AAD+DwAAAAAAAAA+AAAAAAD+Az8AAAAAAAD8HvAfKAD8DwAAAAAAAAAfAAAAAAD/gB8AAAAAAAD+D/gPfAD+HwAAAAAAAIAPAAAAAIA/wA8AAAAAAAj/B/wH/gD8HwAAAAAAAMAPAAAAAPB/4AcAAAAB4J//A/4DfwD4HwAAAAAAAMAHAAAAAPy/8gMAAOAD/g//8f+BPwDwPwAAAAAAAOAHAAAAAP7f8QEAAPwB/4f/+D/AHwD4HwAAAAAAAPADAAAAAP//+AAAAP7A/+NX/Pf/jw/wPwAAAAAAAPABAAAAgP//AAAAAH/g//ED/vu/51/gPwAAAAAAAPgDAAAAwP9/AAAAgD/wf/wB//0f8T/+PwAAAAAAAPwBAAAA8D8/AAAAwB/4P/6A//8P+L//PwAAAAAAAPwBAAAA/o8fAAAA4Af0AX/A//8H/N//PwAAAAAAAP4AAADc/8cPAAAA8AMPwD+A//8D/u/vHwAAAAAAAP4AAIDv/+MHAAD8UuAH4B+A//8B/PfnPwAAAAAAAP4AAMD3//EBAAD/B/wD8APgv34A6PvjHwAAAAAAAP8AAPD7f3AAAID/B/4B+AHwHz4ACPz/PwAAAAAAAH8AAPj9CwAAAMD/w/8A/AD4zx9AD/7/HwAAAAAAAP8AAP5cAAAAAOD/4X8AfgD84w/gB/z/HwAAAAAAgH8AAH8AAAAAAPD/8A9APwD+8Af8A/7/HwAAAAAAgP8AgB8AAAAAAOB/+AH6HwA/+AP+Af/vDwAAAAAAgH8AwA8AAAAAAKA//AD/DwAf/AD/gP/zDwAAAAAAgP8A4AEAAAAAAAA+FMD/AYAfHuB/wH/4DwAAAAAAgH8AIAAAAAAAAAA/AOB/AMAPAvw/4Av8BwAAAAAAwP8AAAAAAAAAAIA/APA/AOAHAP8H+AD+BwAAAAAAgH8AAAAAAAAAAMAfVPgPAPADwP8CfkD/AwAAAAAAwP8AAAAAAAAAAOCff/wBAPgB4D8AP/D/AwAAAAAAgP8BAAAAAAAAAPDPfz4AAHgA8A+AH/z7AQAAAAAAgP8AAAAAAAAAoPLnPwAAADwA+AfAD/79AAAAAAAAgP8BAAAAAAAA9PnzHwAAAP4B/APgh//8AAAAAAAAgP8DAAAAAAAA/vD5DwAAgP8AfgDwwX98AAAAAAAAgP8BAAAAAACAfyD8BwAAwH8APl458D9+AAAAAAAAAP8DAAAAAADAPwD8AQAA4D+Aj/8D/g8/AAAAAAAAgP8HAAAAAADgHwAAAAAA8B/w3/+B/wMfAAAAAAAAAP8HAAAAAADwBwAAAAAA+Af47//Af4APAAAAAAAAAP4HAAAAAAD4AwAAAAAAKAD893/gB4AHAAAAAAAAAP8PAAAAAAB8AQAAAAAAAAD++z/wA8ADAAAAAAAAAP4fAAAAAAA4AAAAAAAAAAD/oQ74AeABAAAAAAAAAPw/AAAAAAAAAAAAAAAAAIB/AAD8APAAAAAAAAAAAPh/AAAAAAAAAAAAAAAAAAAAAAA8AHgAAAAAAAAAAPz/AAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAPj/AQAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAPD/AwAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAOD/BwAAAAAAAAAAAAQAAAAAAAAAwAcAAAAAAAAAAMD/DwAAAAAAAAAAgA8AAAAAAAAA4AMAAAAAAAAAAID/HwAAAAAAAAAAwA8AAAAAAAAA8AEAAAAAAAAAAAD/PwAAAAAAAAAA4A8AAAAAAAAA/AAAAAAAAAAAAAD+fwAAAAAAAAAA8AcEAAAAAAAAPwAAAAAAAAAAAAD8/wAAAAAAAAAA+OMvAAAAAACAHwAAAAAAAAAAAAD4/wEAAAAAAAAA/P0fAAAAAADgDwAAAAAAAAAAAADw/wsAAAAAAAAA/P4vAAAAAAD4AwAAAAAAAAAAAADg/x8AAAAAAAAA/P//BwAAAAD+AQAAAAAAAAAAAADA/z8AAAAAALwA+P//DwAAAIB/AAAAAAAAAAAAAACA/38BAAAAAP4A/v//BwAAAOA/AAAAAAAAAAAAAAAA//8DAAAAAP+BP///AwAAAPgPAAAAAAAAAAAAAAAA/v8DAAAAgP/An/f/AQAAAP8DAAAAAAAAAAAAAAAA8P8BAAAAwH/gx9//AAAA4P8AAAAAAAAAAAAAAAAA4P8AAAAA4D/w458qAAAA/D8AAAAAAAAAAAAAAAAAwH8AAAAAwB/48Q8AAACA/w8AAAAAAAAAAAAAAAAAAD4AAAAAgAL8+R8AAADw/wMAAAAAAAAAAAAAAAAAABQAAAAAAOD//w8AAAD+fwAAAAAAAAAAAAAAAAAAAAAAAAAAAPD/+QcAAND/DwAAAAAAAAAAAAAAAAAAAAAAAAAAAPj//AMAgP7/AQAAAAAAAAAAAAAAAAAAAAAAAABUAfx/6AEA9P//AAAAAAAAAAAAAAAAAAAAAAAAAAD+r/4/QADo//8HAAAAAAAAAAAAAAAAAAAAAAAAAAD///9fRfX///8AAAAAAAAAAAAAAAAAAAAAAAAAAID//////////x8AAAAAAAAAAAAAAAAAAAAAAAAAAMD//////////wIAAAAAAAAAAAAAAAAAAAAAAAAAAOD/////////FwAAAAAAAAAAAAAAAAAAAAAAAAAAAID+//////+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABA/f///18BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKqqKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
 }
];
// is sprite pixel k land?
export const isLandPx = (t, k)=>{ if (!t._land) t._land = typeof atob === 'function' ? Uint8Array.from(atob(t.land), c=>c.charCodeAt(0)) : Uint8Array.from(Buffer.from(t.land, 'base64')); return (t._land[k>>3] >> (k & 7)) & 1; };
